create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.set_updated_at() from public, anon, authenticated;

create table public.characters (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  class_id text not null,
  level integer not null default 1 check (level >= 1),
  xp bigint not null default 0 check (xp >= 0),
  hp integer not null default 100 check (hp >= 0),
  ki integer not null default 100 check (ki >= 0),
  gold bigint not null default 0 check (gold >= 0),
  map_id text not null default 'world',
  x double precision not null default 0,
  y double precision not null default 0,
  state jsonb not null default '{}'::jsonb,
  last_played_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint characters_name_length check (char_length(name) between 2 and 12),
  constraint characters_class_id check (class_id in ('saiya', 'humano', 'nameko', 'lutadora'))
);

create unique index characters_name_ci_unique on public.characters (lower(name));
create index characters_user_id_idx on public.characters (user_id);
create index characters_last_played_idx on public.characters (user_id, last_played_at desc nulls last);

create trigger characters_set_updated_at
before update on public.characters
for each row execute function private.set_updated_at();

create table public.inventory (
  id bigint generated by default as identity primary key,
  character_id uuid not null references public.characters(id) on delete cascade,
  item_id text not null,
  quantity integer not null default 1 check (quantity > 0),
  slot integer check (slot is null or slot >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index inventory_character_id_idx on public.inventory (character_id);
create unique index inventory_character_slot_unique
  on public.inventory (character_id, slot)
  where slot is not null;

create trigger inventory_set_updated_at
before update on public.inventory
for each row execute function private.set_updated_at();

create table public.quest_progress (
  character_id uuid not null references public.characters(id) on delete cascade,
  quest_id text not null,
  status text not null default 'active' check (status in ('active', 'completed', 'failed')),
  progress integer not null default 0 check (progress >= 0),
  data jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (character_id, quest_id)
);

create index quest_progress_character_id_idx on public.quest_progress (character_id);

create trigger quest_progress_set_updated_at
before update on public.quest_progress
for each row execute function private.set_updated_at();

create table public.character_flags (
  character_id uuid not null references public.characters(id) on delete cascade,
  flag text not null,
  value jsonb not null default 'true'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (character_id, flag)
);

create trigger character_flags_set_updated_at
before update on public.character_flags
for each row execute function private.set_updated_at();

alter table public.characters enable row level security;
alter table public.inventory enable row level security;
alter table public.quest_progress enable row level security;
alter table public.character_flags enable row level security;

revoke all on table public.characters from anon;
revoke all on table public.inventory from anon;
revoke all on table public.quest_progress from anon;
revoke all on table public.character_flags from anon;

grant select, insert, update, delete on table public.characters to authenticated;
grant select, insert, update, delete on table public.inventory to authenticated;
grant select, insert, update, delete on table public.quest_progress to authenticated;
grant select, insert, update, delete on table public.character_flags to authenticated;

grant all on table public.characters to service_role;
grant all on table public.inventory to service_role;
grant all on table public.quest_progress to service_role;
grant all on table public.character_flags to service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;

create policy "characters_select_own"
on public.characters for select to authenticated
using ((select auth.uid()) = user_id);

create policy "characters_insert_own"
on public.characters for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "characters_update_own"
on public.characters for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "characters_delete_own"
on public.characters for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "inventory_select_own"
on public.inventory for select to authenticated
using (exists (
  select 1 from public.characters c
  where c.id = inventory.character_id
    and c.user_id = (select auth.uid())
));

create policy "inventory_insert_own"
on public.inventory for insert to authenticated
with check (exists (
  select 1 from public.characters c
  where c.id = inventory.character_id
    and c.user_id = (select auth.uid())
));

create policy "inventory_update_own"
on public.inventory for update to authenticated
using (exists (
  select 1 from public.characters c
  where c.id = inventory.character_id
    and c.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.characters c
  where c.id = inventory.character_id
    and c.user_id = (select auth.uid())
));

create policy "inventory_delete_own"
on public.inventory for delete to authenticated
using (exists (
  select 1 from public.characters c
  where c.id = inventory.character_id
    and c.user_id = (select auth.uid())
));

create policy "quest_progress_select_own"
on public.quest_progress for select to authenticated
using (exists (
  select 1 from public.characters c
  where c.id = quest_progress.character_id
    and c.user_id = (select auth.uid())
));

create policy "quest_progress_insert_own"
on public.quest_progress for insert to authenticated
with check (exists (
  select 1 from public.characters c
  where c.id = quest_progress.character_id
    and c.user_id = (select auth.uid())
));

create policy "quest_progress_update_own"
on public.quest_progress for update to authenticated
using (exists (
  select 1 from public.characters c
  where c.id = quest_progress.character_id
    and c.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.characters c
  where c.id = quest_progress.character_id
    and c.user_id = (select auth.uid())
));

create policy "quest_progress_delete_own"
on public.quest_progress for delete to authenticated
using (exists (
  select 1 from public.characters c
  where c.id = quest_progress.character_id
    and c.user_id = (select auth.uid())
));

create policy "character_flags_select_own"
on public.character_flags for select to authenticated
using (exists (
  select 1 from public.characters c
  where c.id = character_flags.character_id
    and c.user_id = (select auth.uid())
));

create policy "character_flags_insert_own"
on public.character_flags for insert to authenticated
with check (exists (
  select 1 from public.characters c
  where c.id = character_flags.character_id
    and c.user_id = (select auth.uid())
));

create policy "character_flags_update_own"
on public.character_flags for update to authenticated
using (exists (
  select 1 from public.characters c
  where c.id = character_flags.character_id
    and c.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.characters c
  where c.id = character_flags.character_id
    and c.user_id = (select auth.uid())
));

create policy "character_flags_delete_own"
on public.character_flags for delete to authenticated
using (exists (
  select 1 from public.characters c
  where c.id = character_flags.character_id
    and c.user_id = (select auth.uid())
));

comment on table public.characters is
  'Persistent Dragon Saga Online player characters. state stores flexible game-save data during migration from localStorage.';

comment on column public.characters.state is
  'Flexible JSON state for gameplay fields not yet normalized. Server-authoritative fields can be moved to dedicated columns over time.';
